[search_strategy]
n_jobs = 1
n_trials = 128
timeout = 28800.0
sampler = "TPE"
acc_threshold = 0.8
avg_bitwidth_threshold = 5.0
sort_by = [ "avg_bitwidth", "accuracy",]

[search_estimator]
alpha_acc = 1
alpha_mem_density = 0.2
num_samples = 512
compare_to = 32

[search_space]
extend_quant_config_seed_first = true

[search_space.quant_config_seed.default]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 6, 5, 4, 3,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 5, 4, 3, 2,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 5, 4, 3, 2,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]
