from .configuration_opt import OPTQuantizedConfig
from .profiler_opt import profile_opt_quantized
from .modeling_opt import OPTQuantizedForCausalLM, OPTQuantizedForSequenceClassification
from .quant_config_opt import parse_opt_quantized_config
