[search_strategy]
n_jobs = 1
n_trials = 64
timeout = 28800.0
sampler = "TPE"
acc_threshold = 0.5
avg_bitwidth_threshold = 7.0
sort_by = [ "avg_bitwidth", "accuracy",]

[search_estimator]
alpha_acc = 1
alpha_mem_density = 0.1
compare_to = 32

[search_space]
extend_quant_config_seed_first = false

[search_space.quant_config_seed.default]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 7, 6, 5, 4,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]

[search_space.quant_config_seed.model_layer.fc1]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 6, 5, 4, 3,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]

[search_space.quant_config_seed.model_layer.fc2]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 6, 5, 4, 3,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]

[search_space.quant_config_seed.model_layer.self_attn.q_proj]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 6, 5, 4, 3,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]

[search_space.quant_config_seed.model_layer.self_attn.k_proj]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 6, 5, 4, 3,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]

[search_space.quant_config_seed.model_layer.self_attn.v_proj]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 6, 5, 4, 3,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]

[search_space.quant_config_seed.model_layer.self_attn.out_proj]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 6, 5, 4, 3,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]

[search_space.quant_config_seed.model_layer.self_attn.bmm_0]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 6, 5, 4, 3,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]

[search_space.quant_config_seed.model_layer.self_attn.bmm_1]
name = [ "block_fp",]
bypass = [ "!ast!False",]
is_ptq = [ "!ast!True",]
data_in_width = [ 7, 6, 5, 4,]
data_in_exponent_width = [ 8,]
data_in_exponent_bias = [ "!ast!None",]
data_in_block_size = [ "!ast![1, 16]",]
weight_width = [ 6, 5, 4, 3,]
weight_exponent_width = [ 8,]
weight_exponent_bias = [ "!ast!None",]
weight_block_size = [ "!ast![1, 16]",]
bias_width = [ 6, 5, 4, 3,]
bias_exponent_width = [ 8,]
bias_exponent_bias = [ "!ast!None",]
bias_block_size = [ "!ast![1, 16]",]
